# Generated by Django 4.2.1 on 2023-07-28 12:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencia',
            name='nivel_administrativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competencias', to='indicadores.niveladministrativo'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='fecha',
            field=models.DateField(default=datetime.date(2023, 7, 28)),
        ),
    ]
