# Generated by Django 4.2.1 on 2023-07-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0002_evaluacion_porcentaje_objetivos_evaluado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='porcentaje_competencias_evaluado',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='porcentaje_competencias_evaluador',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
    ]
