# Generated by Django 4.2.1 on 2023-07-26 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0002_alter_empleado_user_alter_evaluacion_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestaobjetivo',
            name='objetivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta', to='indicadores.objetivo'),
        ),
    ]
