# Generated by Django 4.2.1 on 2023-07-29 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0003_evaluacion_porcentaje_competencias_evaluado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluacion',
            old_name='porcentaje_total',
            new_name='resultado_final',
        ),
    ]
