# Generated by Django 4.2.1 on 2023-07-28 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indicadores', '0003_lider_nivel_administrativo_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='director', to=settings.AUTH_USER_MODEL),
        ),
    ]
