# Generated by Django 4.2.1 on 2023-07-29 21:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0004_rename_porcentaje_total_evaluacion_resultado_final'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(default=datetime.date(2023, 7, 29), verbose_name='año')),
                ('resultado', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_anuales', to='indicadores.director')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_anuales', to='indicadores.empleado')),
                ('lider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_anuales', to='indicadores.lider')),
            ],
            options={
                'verbose_name_plural': 'Informes Anuales',
            },
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='informe_anual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='indicadores.informeanual'),
        ),
    ]
